server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zhangweikuo1997+
    driver-class-name: com.mysql.cj.jdbc.Driver
  #application:
    #userf微服务的名称 不叫eureka server了
    #name: userservice
  #nacos的配置属于spring
  #cloud:
    #nacos:
      #server-addr: localhost:8848
      #discovery:
        #自定义集群名称
        #cluster-name: Hangzhou
#eureka:
#  client:
#    service-url:
#      #eureka的地址信息，因为eureka也是一个微服务，所以在项目启动的时候eureka也会把自己注册到eureka上去
#      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地配置name属性



